title: 我的个人网站
email: your@email.com
description: 一个学生的个人博客
baseurl: ""
url: "https://yourusername.github.io" 
theme: jekyll-theme-minimal
plugins:
  - jekyll-paginate
paginate: 5
paginate_path: "/blog/page:num/"